[package]
name = "opencv_ailia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ailia = { path="../rust_wrapper/" }
opencv = {version = "0.91.3", features = ["clang-runtime"]}
anyhow = "1.0.68"
